# Generated by Django 4.0.10 on 2023-04-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_delete_quillpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Body',
        ),
    ]
