# Generated by Django 4.0.10 on 2023-04-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='description',
            field=models.TextField(default='n/a', max_length=600),
            preserve_default=False,
        ),
    ]
