# Generated by Django 4.0.10 on 2023-04-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_remove_quillpost_title_delete_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.FileField(default='n/a', upload_to='review_images/{self.title}'),
            preserve_default=False,
        ),
    ]
