# Generated by Django 4.0.10 on 2023-04-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='images',
        ),
        migrations.AddField(
            model_name='review',
            name='img_one',
            field=models.FileField(default='n/a', upload_to='review_img_1/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='img_three',
            field=models.FileField(default='n/a', upload_to='review_img_3/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='img_two',
            field=models.FileField(default='n/a', upload_to='review_img_2/%m/%d'),
            preserve_default=False,
        ),
    ]
