# Generated by Django 4.0.10 on 2023-04-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_quillpost_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
    ]
