# Generated by Django 4.0.10 on 2023-04-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_quillpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quillpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='title',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
