# Generated by Django 4.0.10 on 2023-04-11 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_text', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='audio_files/%m/%d/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.title')),
            ],
        ),
    ]
